# Generated by Django 2.2 on 2019-04-28 17:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('datame', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='reviews',
        ),
        migrations.RemoveField(
            model_name='datascientist',
            name='reviews',
        ),
    ]
