# Generated by Django 2.1.7 on 2019-05-01 12:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('datame', '0002_auto_20190428_1726'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='datascientist',
            name='email',
        ),
    ]
